# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2020-05-27 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='mobile',
        ),
        migrations.AlterField(
            model_name='dataweb',
            name='last_ip',
            field=models.CharField(max_length=20, verbose_name='连接ip'),
        ),
    ]
